# Generated by Django 3.2.4 on 2021-09-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorid', models.CharField(max_length=100)),
                ('bookcategory', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('useful', models.CharField(max_length=100)),
                ('coverpic', models.ImageField(default='', upload_to='static/addbooks/')),
                ('charge', models.IntegerField(max_length=100)),
                ('uploaddate', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cpic', models.ImageField(default='', upload_to='static/category/')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=100)),
                ('citypic', models.ImageField(default='', upload_to='static/city/')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('ppic', models.ImageField(default='', upload_to='static/signup/')),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('yes', models.CharField(max_length=100)),
                ('regdate', models.DateField(max_length=100)),
                ('status', models.BooleanField(max_length=100)),
            ],
        ),
    ]
