# Generated by Django 3.2.4 on 2021-09-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='charge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='uploaddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='login',
            name='regdate',
            field=models.DateField(),
        ),
    ]
