# Generated by Django 3.2.4 on 2021-09-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior', '0002_auto_20210930_0252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='reg',
        ),
        migrations.RenameModel(
            old_name='signin',
            new_name='signi',
        ),
    ]
