# Generated by Django 3.2.4 on 2021-09-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior', '0003_auto_20210930_0350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signi',
            new_name='login',
        ),
    ]
