# Generated by Django 3.2.4 on 2021-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior', '0004_rename_signi_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
