# Generated by Django 3.2.4 on 2021-10-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior', '0006_auto_20210930_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newname', models.CharField(max_length=100)),
                ('newpic', models.ImageField(default='', upload_to='static/newrelesed/')),
            ],
        ),
        migrations.RemoveField(
            model_name='addbooks',
            name='uploaddate',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=600),
        ),
    ]
